# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResponseTracePos(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsResponseTracePos(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResponseTracePos()
        x.Init(buf, n + offset)
        return x

    # ResponseTracePos
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResponseTracePos
    def Recordings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from fbs.RecordingTracePos import RecordingTracePos
            obj = RecordingTracePos()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ResponseTracePos
    def RecordingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ResponseTracePos
    def RecordingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ResponseTracePosStart(builder): builder.StartObject(1)
def ResponseTracePosAddRecordings(builder, recordings): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(recordings), 0)
def ResponseTracePosStartRecordingsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ResponseTracePosEnd(builder): return builder.EndObject()
