# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Array3MetaFlow(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Array3MetaFlow()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArray3MetaFlow(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Array3MetaFlow
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Array3MetaFlow
    def Nx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Array3MetaFlow
    def Ny(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Array3MetaFlow
    def Nt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Array3MetaFlow
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Array3MetaFlow
    def ParentName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Array3MetaFlow
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from fbs.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Array3MetaFlowStart(builder): builder.StartObject(6)
def Start(builder):
    return Array3MetaFlowStart(builder)
def Array3MetaFlowAddNx(builder, nx): builder.PrependInt32Slot(0, nx, 0)
def AddNx(builder, nx):
    return Array3MetaFlowAddNx(builder, nx)
def Array3MetaFlowAddNy(builder, ny): builder.PrependInt32Slot(1, ny, 0)
def AddNy(builder, ny):
    return Array3MetaFlowAddNy(builder, ny)
def Array3MetaFlowAddNt(builder, nt): builder.PrependInt32Slot(2, nt, 0)
def AddNt(builder, nt):
    return Array3MetaFlowAddNt(builder, nt)
def Array3MetaFlowAddName(builder, name): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def AddName(builder, name):
    return Array3MetaFlowAddName(builder, name)
def Array3MetaFlowAddParentName(builder, parentName): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(parentName), 0)
def AddParentName(builder, parentName):
    return Array3MetaFlowAddParentName(builder, parentName)
def Array3MetaFlowAddColor(builder, color): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)
def AddColor(builder, color):
    return Array3MetaFlowAddColor(builder, color)
def Array3MetaFlowEnd(builder): return builder.EndObject()
def End(builder):
    return Array3MetaFlowEnd(builder)