# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

from enum import IntEnum
class BitRange(IntEnum):
    AUTODETECT = 0
    MINMAX = 1
    UINT8 = 2
    UINT10 = 3
    UINT12 = 4
    UINT16 = 5
    FLOAT = 6
    DIFF = 7
    PHASE = 8
    PHASE_DIFF = 9
    INT8 = 10
