# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class BitRange(object):
    AUTODETECT = 0
    UINT8 = 1
    UINT10 = 2
    UINT12 = 3
    UINT16 = 4
    FLOAT = 5
    DIFF = 6
    PHASE = 7
    PHASE_DIFF = 8
