# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

from enum import IntEnum
class ColorMap(IntEnum):
    DEFAULT = 0
    GRAY = 1
    HSV = 2
    BLACKBODY = 3
    VIRIDIS = 4
    PRGn = 5
    PRGn_POS = 6
    PRGn_NEG = 7
    RdBu = 8
