# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class ColorMap(object):
    DEFAULT = 0
    GRAY = 1
    HSV = 2
    BLACKBODY = 3
    VIRIDIS = 4
    DIFF = 5
    DIFF_POS = 6
    DIFF_NEG = 7
