# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

from enum import IntEnum
class Data(IntEnum):
    NONE = 0
    Filepaths = 1
    Array3Meta = 2
    Array3MetaFlow = 3
    Array3DataChunkf = 4
    Array3DataChunku8 = 5
    Array3DataChunku16 = 6
    VideoExport = 7
    PointsVideo = 8
    CloseVideo = 9
    Quit = 10
    CloseAllVideos = 11
    SetPlaybackSpeed = 12
    Play = 13
    Pause = 14
    SetFrame = 15
    GetTracePos = 16
    TracesResponse = 17
