# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

from enum import IntEnum
class Data(IntEnum):
    NONE = 0
    Filepaths = 1
    Array3Meta = 2
    Array3MetaFlow = 3
    Array3DataChunkf = 4
    Array3DataChunku8 = 5
    Array3DataChunku16 = 6
    Request = 7
    PointsVideo = 8
    VideoID = 9
