# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Filepaths(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Filepaths()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFilepaths(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Filepaths
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Filepaths
    def File(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Filepaths
    def FileLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Filepaths
    def FileIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def FilepathsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddFile(builder, file): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(file), 0)
def FilepathsAddFile(builder, file):
    """This method is deprecated. Please switch to AddFile."""
    return AddFile(builder, file)
def StartFileVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FilepathsStartFileVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartFileVector(builder, numElems)
def End(builder): return builder.EndObject()
def FilepathsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)