# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .VideoMetadata import VideoMetadata
from typing import Optional
np = import_numpy()

class MetadataResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MetadataResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMetadataResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MetadataResponse
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MetadataResponse
    def Videos(self, j: int) -> Optional[VideoMetadata]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = VideoMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MetadataResponse
    def VideosLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetadataResponse
    def VideosIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def MetadataResponseStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    MetadataResponseStart(builder)

def MetadataResponseAddVideos(builder: flatbuffers.Builder, videos: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(videos), 0)

def AddVideos(builder: flatbuffers.Builder, videos: int):
    MetadataResponseAddVideos(builder, videos)

def MetadataResponseStartVideosVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartVideosVector(builder, numElems: int) -> int:
    return MetadataResponseStartVideosVector(builder, numElems)

def MetadataResponseEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MetadataResponseEnd(builder)
