# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

from enum import IntEnum
class OpacityFunction(IntEnum):
    NONE = 0
    LINEAR = 1
    LINEAR_R = 2
    CENTERED = 3
    FIXED_100 = 4
    FIXED_75 = 5
    FIXED_50 = 6
    FIXED_25 = 7
    FIXED_0 = 8
