# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .RecordingTrace import RecordingTrace
from typing import Optional
np = import_numpy()

class RecordingTraces(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RecordingTraces()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRecordingTraces(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RecordingTraces
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RecordingTraces
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RecordingTraces
    def Traces(self, j: int) -> Optional[RecordingTrace]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = RecordingTrace()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RecordingTraces
    def TracesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RecordingTraces
    def TracesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def RecordingTracesStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    RecordingTracesStart(builder)

def RecordingTracesAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    RecordingTracesAddName(builder, name)

def RecordingTracesAddTraces(builder: flatbuffers.Builder, traces: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(traces), 0)

def AddTraces(builder: flatbuffers.Builder, traces: int):
    RecordingTracesAddTraces(builder, traces)

def RecordingTracesStartTracesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTracesVector(builder, numElems: int) -> int:
    return RecordingTracesStartTracesVector(builder, numElems)

def RecordingTracesEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RecordingTracesEnd(builder)
