# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class SetPlaybackSpeed(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetPlaybackSpeed()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetPlaybackSpeed(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetPlaybackSpeed
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetPlaybackSpeed
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetPlaybackSpeedStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    SetPlaybackSpeedStart(builder)

def SetPlaybackSpeedAddSpeed(builder: flatbuffers.Builder, speed: float):
    builder.PrependFloat32Slot(0, speed, 0.0)

def AddSpeed(builder: flatbuffers.Builder, speed: float):
    SetPlaybackSpeedAddSpeed(builder, speed)

def SetPlaybackSpeedEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SetPlaybackSpeedEnd(builder)
