# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .DictEntry import DictEntry
from typing import Optional
np = import_numpy()

class VideoMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VideoMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVideoMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VideoMetadata
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VideoMetadata
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VideoMetadata
    def Nx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VideoMetadata
    def Ny(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VideoMetadata
    def Nt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VideoMetadata
    def Nc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VideoMetadata
    def CurrentFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VideoMetadata
    def Vmin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VideoMetadata
    def Vmax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VideoMetadata
    def Colormap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VideoMetadata
    def Bitrange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VideoMetadata
    def Metadata(self, j: int) -> Optional[DictEntry]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DictEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VideoMetadata
    def MetadataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VideoMetadata
    def MetadataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

def VideoMetadataStart(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    VideoMetadataStart(builder)

def VideoMetadataAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    VideoMetadataAddName(builder, name)

def VideoMetadataAddNx(builder: flatbuffers.Builder, nx: int):
    builder.PrependInt32Slot(1, nx, 0)

def AddNx(builder: flatbuffers.Builder, nx: int):
    VideoMetadataAddNx(builder, nx)

def VideoMetadataAddNy(builder: flatbuffers.Builder, ny: int):
    builder.PrependInt32Slot(2, ny, 0)

def AddNy(builder: flatbuffers.Builder, ny: int):
    VideoMetadataAddNy(builder, ny)

def VideoMetadataAddNt(builder: flatbuffers.Builder, nt: int):
    builder.PrependInt32Slot(3, nt, 0)

def AddNt(builder: flatbuffers.Builder, nt: int):
    VideoMetadataAddNt(builder, nt)

def VideoMetadataAddNc(builder: flatbuffers.Builder, nc: int):
    builder.PrependInt32Slot(4, nc, 0)

def AddNc(builder: flatbuffers.Builder, nc: int):
    VideoMetadataAddNc(builder, nc)

def VideoMetadataAddCurrentFrame(builder: flatbuffers.Builder, currentFrame: int):
    builder.PrependInt32Slot(5, currentFrame, 0)

def AddCurrentFrame(builder: flatbuffers.Builder, currentFrame: int):
    VideoMetadataAddCurrentFrame(builder, currentFrame)

def VideoMetadataAddVmin(builder: flatbuffers.Builder, vmin: float):
    builder.PrependFloat32Slot(6, vmin, 0.0)

def AddVmin(builder: flatbuffers.Builder, vmin: float):
    VideoMetadataAddVmin(builder, vmin)

def VideoMetadataAddVmax(builder: flatbuffers.Builder, vmax: float):
    builder.PrependFloat32Slot(7, vmax, 0.0)

def AddVmax(builder: flatbuffers.Builder, vmax: float):
    VideoMetadataAddVmax(builder, vmax)

def VideoMetadataAddColormap(builder: flatbuffers.Builder, colormap: int):
    builder.PrependInt32Slot(8, colormap, 0)

def AddColormap(builder: flatbuffers.Builder, colormap: int):
    VideoMetadataAddColormap(builder, colormap)

def VideoMetadataAddBitrange(builder: flatbuffers.Builder, bitrange: int):
    builder.PrependInt32Slot(9, bitrange, 0)

def AddBitrange(builder: flatbuffers.Builder, bitrange: int):
    VideoMetadataAddBitrange(builder, bitrange)

def VideoMetadataAddMetadata(builder: flatbuffers.Builder, metadata: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(metadata), 0)

def AddMetadata(builder: flatbuffers.Builder, metadata: int):
    VideoMetadataAddMetadata(builder, metadata)

def VideoMetadataStartMetadataVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartMetadataVector(builder, numElems: int) -> int:
    return VideoMetadataStartMetadataVector(builder, numElems)

def VideoMetadataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return VideoMetadataEnd(builder)
