# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VideoID(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VideoID()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVideoID(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VideoID
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VideoID
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VideoID
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def VideoIDStart(builder): builder.StartObject(2)
def Start(builder):
    return VideoIDStart(builder)
def VideoIDAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def AddId(builder, id):
    return VideoIDAddId(builder, id)
def VideoIDAddError(builder, error): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)
def AddError(builder, error):
    return VideoIDAddError(builder, error)
def VideoIDEnd(builder): return builder.EndObject()
def End(builder):
    return VideoIDEnd(builder)