# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class Filepaths(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFilepaths(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Filepaths()
        x.Init(buf, n + offset)
        return x

    # Filepaths
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Filepaths
    def File(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Filepaths
    def FileLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def FilepathsStart(builder): builder.StartObject(1)
def FilepathsAddFile(builder, file): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(file), 0)
def FilepathsStartFileVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FilepathsEnd(builder): return builder.EndObject()
