# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class Data(object):
    NONE = 0
    Filepaths = 1
    Array3Meta = 2
    Array3MetaFlow = 3
    Array3DataChunkf = 4
    Array3DataChunku16 = 5

